twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    auto_reload: '%kernel.debug%'
    date:
        format: d.m.Y H:i
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap.html.twig']