site:
    resource: 'site.yaml'
company:
    resource: 'company.yaml'
    trailing_slash_on_root: false
    prefix: /company
catalog:
    resource: 'catalog.yaml'
    prefix: /catalog
support:
    resource: 'support.yaml'
partners:
    resource: 'partners.yaml'
    prefix: /partners
buy:
    path: /buy
    defaults: { template: 'buy/index.html.twig' }
contacts:
    path: /company/contacts