home:
    path: /

redirects:
    resource: 'routes/redirects.yaml'
    controller: App\Controller\RedirectController::urlRedirectAction
    defaults:
        permanent: true

logout:
    path: /account/logout

static:
    resource: 'routes/base.yaml'
    controller: App\Controller\TemplateController
    defaults:
        maxAge: 86400
        sharedAge: 86400